config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  devise_for :users
  root 'application#index'

  namespace :admin do
    root 'main#index'
    namespace :manage do
      resources :users, only: %i[index create]
    end
    resources :main, only: :index
  end

  scope module: 'users' do
    root 'main#index'
    scope module: 'manage' do
      resources :companies do
        resources :positions
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  scope :owner, ->(user) { where(user_id: user.id) }

  has_many :employments
  has_many :users, through: :employments
  has_many :positions

  validates :unp, presence: true, length: { is: 9 }
  validates :name, presence: true, length: { in: 2..100 }

end

app/models/employment.rb
class Employment < ApplicationRecord
  belongs_to :company
  belongs_to :employee
end

app/models/position.rb
class Position < ApplicationRecord
  scope :by_company, ->(company_id) { where(company_id: company_id) }

  belongs_to :company

  validates :title, presence: true, length: { in: 2..50 }, uniqueness: { scope: :company }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :employments
  has_many :companies, through: :employments

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable
end

app/controllers/admin/main_controller.rb
# frozen_string_literal: true

module Admin
  class MainController < AdminController
    def index; end
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  http_basic_authenticate_with name: ENV['admin_login'],
                               password: ENV['admin_password']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ReactOnRails::Controller

  def index; end
end

app/controllers/users/main_controller.rb
# frozen_string_literal: true

module Users
  class MainController < UsersController
    def index; end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to t('main_brand_name'), root_path, { class: 'navbar-brand', style: ' color: darkorange; font-size: 30px;'}
  %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#navbarNavAltMarkup'}, aria: { controls: 'navbarNavAltMarkup', expanded: 'false', label: 'Toggle navigation' }}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNavAltMarkup
    .navbar-nav
      = link_to admin_manage_users_path, class: 'nav-item nav-link' do
        = fa_icon 'users', text: t('users.nav_link')

app/views/admin/index.html.haml
%h1
  Admin
  %span.badge.badge-danger area

app/views/application/_header.html.haml
%nav.navbar.navbar-light.bg-light
  = link_to t('main_brand_name'), root_path, { class: 'navbar-brand', style: ' color: darkorange; font-size: 30px;'}
  - if user_signed_in?
    = simple_form_for(:user, url: destroy_session_path(:user), html: { role: 'form', class: 'form-inline ml-auto', method: :delete }) do |f|
      .input-group
        .input-group-prepend
          %span.input-group-text= current_user.email
        .input-group-append
          = f.button :submit, t('logout_button'), class: 'btn btn-outline-success'
  - else
    = simple_form_for(:user, url: session_path(:user), html: { role: 'form', class: 'form-inline ml-auto'}) do |f|
      .input-group
        .input-group-prepend
          %span.input-group-text &#64
        = f.input_field :email, placeholder: t('email_placeholder'), id: 'header_user_email', class: 'form-control'
        .input-group-prepend
          %span.input-group-text &#128274
        = f.input_field :password, placeholder: t('password_placeholder'), id: 'header_user_password', class: 'form-control'
        .input-group-append
          = f.button :submit, t('login_button'), class: 'btn btn-outline-success'

app/views/application/_messages.html.haml
- flash.each do |key, value|
  %div{ class: "alert alert-#{key}" }
    %a.close{ href: '#', data: { dismiss: 'alert' }} &times;
    %ul
      %li= value

app/views/application/index.html.haml
%h1
  Welcome to ESCADRA
  %span.badge.badge-primary= user_signed_in? ? current_user.email : t('guest_name')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= t('main_brand_name')
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag    'escadra-bundle'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'header'
    = redux_store_hydration_data
    .container
      = render 'messages'
      = yield

app/views/users/index.html.haml
%h1
  User area.
  %br
  Current user:
  %span.badge.badge-primary= current_user.email